repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.8.3
  hooks:
    - id: flake8
      args: ["--ignore", "E501"]  # line length handled by black

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      args: ["-l", "85", "-t", "py38"]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.32.0
  hooks:
    - id: eslint
      language: node
      language_version: system
      args: ["--fix", "--no-ignore"]
      additional_dependencies:
        - eslint@7.32.0
        - eslint-plugin-vue@7.2.0
        - '@typescript-eslint/eslint-plugin@4.15.1'
        - '@typescript-eslint/parser@4.15.1'
        - '@vue/eslint-config-typescript@7.0.0'
