"""Account table

Revision ID: f540e29d896b
Revises:
Create Date: 2021-05-08 13:54:48.014964

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f540e29d896b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    # ### end Alembic commands ###
